'use client'
/**
 * MockupGenerator — in-house mockup tool that replaces Printful for MBA.
 *
 * What it does:
 *   1. User picks a model template (e.g., navy tee on man)
 *   2. User uploads a design PNG (transparent background preferred)
 *   3. Design is positioned + sized on the chest area via mouse drag + slider
 *   4. Displacement-map filter (SVG <feDisplacementMap>) warps the design
 *      to follow the model's fabric folds — gives "printed-on" appearance
 *   5. Multiply blend mode ties the design's lighting to the shirt's
 *   6. User clicks "Generate" → exports a PNG that can be uploaded to Sanity
 *
 * Templates live in /public/mockup-templates/:
 *   navy-tee-male.jpg              — the model photo (1024×1024)
 *   navy-tee-male-displacement.jpg — grayscale displacement map
 *
 * To add a new template: drop a model photo + its displacement map (auto-
 * generated by the bash script in scripts/generate-displacement.sh) plus
 * a JSON entry in TEMPLATES below.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

type Template = {
  id: string
  label: string
  imageUrl: string
  displacementUrl: string
  /** Default chest area as % of template width/height — design auto-centers here */
  defaultChest: { x: number; y: number; width: number }
}

const TEMPLATES: Template[] = [
  {
    id: 'navy-tee-male',
    label: 'Navy Tee · Male Model',
    imageUrl: '/mockup-templates/navy-tee-male.jpg',
    displacementUrl: '/mockup-templates/navy-tee-male-displacement.jpg',
    defaultChest: { x: 50, y: 50, width: 22 },
  },
]

const CANVAS_SIZE = 1024 // output dimensions

export default function MockupGenerator() {
  const [template, setTemplate] = useState<Template>(TEMPLATES[0])
  const [designUrl, setDesignUrl] = useState<string | null>(null)
  const [designName, setDesignName] = useState<string>('design')
  // Position + size as % of template (so it's resolution-independent)
  const [pos, setPos] = useState<{ x: number; y: number }>({ x: 50, y: 50 })
  const [size, setSize] = useState<number>(22) // width in % of template
  const [displacement, setDisplacement] = useState<number>(8) // px of warp
  const [blendMode, setBlendMode] = useState<'multiply' | 'normal' | 'overlay' | 'soft-light'>('multiply')
  const [opacity, setOpacity] = useState<number>(100)
  const [showDispPreview, setShowDispPreview] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [exportedUrl, setExportedUrl] = useState<string | null>(null)

  const canvasRef = useRef<HTMLCanvasElement>(null)
  const stageRef = useRef<HTMLDivElement>(null)

  // Initialize position from template's default chest area
  useEffect(() => {
    setPos({ x: template.defaultChest.x, y: template.defaultChest.y })
    setSize(template.defaultChest.width)
  }, [template])

  // Handle file upload
  const handleFile = useCallback((file: File) => {
    setDesignName(file.name.replace(/\.[^.]+$/, ''))
    const reader = new FileReader()
    reader.onload = (e) => {
      setDesignUrl(e.target?.result as string)
      setExportedUrl(null)
    }
    reader.readAsDataURL(file)
  }, [])

  const onFileInput = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const f = e.target.files?.[0]
      if (f) handleFile(f)
    },
    [handleFile],
  )

  // Drag-to-position the design on the model
  const dragging = useRef(false)
  const onPointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!designUrl) return
    dragging.current = true
    ;(e.target as HTMLElement).setPointerCapture?.(e.pointerId)
  }
  const onPointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!dragging.current || !stageRef.current) return
    const rect = stageRef.current.getBoundingClientRect()
    const x = ((e.clientX - rect.left) / rect.width) * 100
    const y = ((e.clientY - rect.top) / rect.height) * 100
    setPos({ x: Math.max(0, Math.min(100, x)), y: Math.max(0, Math.min(100, y)) })
  }
  const onPointerUp = () => { dragging.current = false }

  // Generate PNG by rendering everything to a real canvas at full resolution
  const handleExport = useCallback(async () => {
    if (!designUrl || !canvasRef.current) return
    setExporting(true)
    setExportedUrl(null)
    try {
      const canvas = canvasRef.current
      canvas.width = CANVAS_SIZE
      canvas.height = CANVAS_SIZE
      const ctx = canvas.getContext('2d')!

      // 1. Load all three images in parallel
      const [tplImg, dispImg, designImg] = await Promise.all([
        loadImage(template.imageUrl),
        loadImage(template.displacementUrl),
        loadImage(designUrl),
      ])

      // 2. Draw the template (model photo) as the base
      ctx.drawImage(tplImg, 0, 0, CANVAS_SIZE, CANVAS_SIZE)

      // 3. Render the design to an offscreen canvas with displacement applied.
      //    Canvas API doesn't have a native displacement filter, so we do it
      //    pixel-by-pixel: for each output pixel, sample the displacement
      //    map to figure out where in the design image to read from.
      const designCanvas = document.createElement('canvas')
      designCanvas.width = CANVAS_SIZE
      designCanvas.height = CANVAS_SIZE
      const dctx = designCanvas.getContext('2d')!

      // Draw design at correct position + scale
      const dWidth = (size / 100) * CANVAS_SIZE
      const dHeight = dWidth // assume square for now
      const dX = (pos.x / 100) * CANVAS_SIZE - dWidth / 2
      const dY = (pos.y / 100) * CANVAS_SIZE - dHeight / 2
      dctx.drawImage(designImg, dX, dY, dWidth, dHeight)

      // 4. Apply displacement via pixel sampling
      const designData = dctx.getImageData(0, 0, CANVAS_SIZE, CANVAS_SIZE)

      // Get displacement map data
      const dispCanvas = document.createElement('canvas')
      dispCanvas.width = CANVAS_SIZE
      dispCanvas.height = CANVAS_SIZE
      dispCanvas.getContext('2d')!.drawImage(dispImg, 0, 0, CANVAS_SIZE, CANVAS_SIZE)
      const dispData = dispCanvas.getContext('2d')!.getImageData(0, 0, CANVAS_SIZE, CANVAS_SIZE)

      // Output canvas
      const outCanvas = document.createElement('canvas')
      outCanvas.width = CANVAS_SIZE
      outCanvas.height = CANVAS_SIZE
      const outData = outCanvas.getContext('2d')!.createImageData(CANVAS_SIZE, CANVAS_SIZE)

      const dispScale = displacement
      for (let y = 0; y < CANVAS_SIZE; y++) {
        for (let x = 0; x < CANVAS_SIZE; x++) {
          const dispIdx = (y * CANVAS_SIZE + x) * 4
          // Use displacement map's luminance as the displacement amount
          const lum = (dispData.data[dispIdx] + dispData.data[dispIdx + 1] + dispData.data[dispIdx + 2]) / 3
          // Map lum (0-255) to displacement (-dispScale to +dispScale)
          const dx = Math.round(((lum - 128) / 128) * dispScale)
          const dy = Math.round(((lum - 128) / 128) * dispScale)
          const srcX = Math.max(0, Math.min(CANVAS_SIZE - 1, x + dx))
          const srcY = Math.max(0, Math.min(CANVAS_SIZE - 1, y + dy))
          const srcIdx = (srcY * CANVAS_SIZE + srcX) * 4
          const outIdx = (y * CANVAS_SIZE + x) * 4
          outData.data[outIdx]     = designData.data[srcIdx]
          outData.data[outIdx + 1] = designData.data[srcIdx + 1]
          outData.data[outIdx + 2] = designData.data[srcIdx + 2]
          outData.data[outIdx + 3] = designData.data[srcIdx + 3]
        }
      }
      outCanvas.getContext('2d')!.putImageData(outData, 0, 0)

      // 5. Composite the warped design onto the template with blend mode
      ctx.globalCompositeOperation = blendMode === 'normal' ? 'source-over' : blendMode as any
      ctx.globalAlpha = opacity / 100
      ctx.drawImage(outCanvas, 0, 0)
      ctx.globalCompositeOperation = 'source-over'
      ctx.globalAlpha = 1

      // 6. Convert to PNG and offer download
      const url = canvas.toDataURL('image/png')
      setExportedUrl(url)
    } catch (err) {
      console.error('[MockupGenerator] export failed:', err)
      alert('Export failed. Check console for details.')
    } finally {
      setExporting(false)
    }
  }, [designUrl, template, pos, size, displacement, blendMode, opacity])

  // Trigger download of the exported PNG
  const downloadExport = () => {
    if (!exportedUrl) return
    const a = document.createElement('a')
    a.href = exportedUrl
    a.download = `mba-mockup-${designName}-${template.id}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
  }

  return (
    <div className="mockup-gen">
      <div className="mockup-gen-header">
        <h1>MBA Mockup Studio</h1>
        <p>Skapa produktbilder utan att betala Printful. Drag designen på modellen, justera, exportera.</p>
      </div>

      <div className="mockup-gen-grid">
        {/* LEFT: Live preview stage */}
        <div className="mockup-gen-stage-wrap">
          <div
            ref={stageRef}
            className="mockup-gen-stage"
            onPointerDown={onPointerDown}
            onPointerMove={onPointerMove}
            onPointerUp={onPointerUp}
            onPointerCancel={onPointerUp}
            style={{ touchAction: 'none' }}
          >
            <img
              src={template.imageUrl}
              alt={template.label}
              className="mockup-gen-template"
              draggable={false}
            />

            {showDispPreview && (
              <img
                src={template.displacementUrl}
                alt="displacement preview"
                className="mockup-gen-template"
                style={{ position: 'absolute', inset: 0, opacity: 0.5 }}
                draggable={false}
              />
            )}

            {designUrl && (
              <div
                className="mockup-gen-design"
                style={{
                  left: `${pos.x}%`,
                  top: `${pos.y}%`,
                  width: `${size}%`,
                  transform: 'translate(-50%, -50%)',
                  mixBlendMode: blendMode,
                  opacity: opacity / 100,
                  // CSS preview can't show displacement; that happens at export time
                }}
              >
                <img src={designUrl} alt="design" draggable={false} />
              </div>
            )}

            {!designUrl && (
              <div className="mockup-gen-placeholder">
                <div>↑</div>
                <div>Ladda upp en design för att börja</div>
              </div>
            )}
          </div>
        </div>

        {/* RIGHT: Controls */}
        <div className="mockup-gen-controls">
          <div className="mockup-gen-section">
            <label className="mockup-gen-label">1. Välj modell</label>
            <select
              value={template.id}
              onChange={(e) =>
                setTemplate(TEMPLATES.find((t) => t.id === e.target.value) || TEMPLATES[0])
              }
            >
              {TEMPLATES.map((t) => (
                <option key={t.id} value={t.id}>{t.label}</option>
              ))}
            </select>
          </div>

          <div className="mockup-gen-section">
            <label className="mockup-gen-label">2. Ladda upp design (PNG)</label>
            <input
              type="file"
              accept="image/png,image/jpeg,image/webp"
              onChange={onFileInput}
            />
            {designUrl && (
              <button
                type="button"
                className="mockup-gen-btn-ghost"
                onClick={() => { setDesignUrl(null); setExportedUrl(null) }}
              >
                Ta bort design
              </button>
            )}
          </div>

          {designUrl && (
            <>
              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  3. Storlek <span>({size.toFixed(0)}%)</span>
                </label>
                <input
                  type="range"
                  min="5"
                  max="60"
                  step="1"
                  value={size}
                  onChange={(e) => setSize(Number(e.target.value))}
                />
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  4. Position
                </label>
                <div style={{ fontSize: 12, opacity: 0.7 }}>
                  Drag designen på bilden för att flytta · X: {pos.x.toFixed(0)}% Y: {pos.y.toFixed(0)}%
                </div>
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  5. Tygveckning <span>({displacement}px)</span>
                </label>
                <input
                  type="range"
                  min="0"
                  max="25"
                  step="1"
                  value={displacement}
                  onChange={(e) => setDisplacement(Number(e.target.value))}
                />
                <div style={{ fontSize: 11, opacity: 0.6, marginTop: 4 }}>
                  Hur mycket designen följer tygets veck. Mer = mer realistiskt, men kan distorsera.
                </div>
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  6. Blend mode
                </label>
                <select
                  value={blendMode}
                  onChange={(e) => setBlendMode(e.target.value as any)}
                >
                  <option value="multiply">Multiply (best för mörk t-shirt)</option>
                  <option value="overlay">Overlay (mer kontrast)</option>
                  <option value="soft-light">Soft Light (mjukare)</option>
                  <option value="normal">Normal (helt opak)</option>
                </select>
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  7. Opacitet <span>({opacity}%)</span>
                </label>
                <input
                  type="range"
                  min="20"
                  max="100"
                  step="1"
                  value={opacity}
                  onChange={(e) => setOpacity(Number(e.target.value))}
                />
              </div>

              <div className="mockup-gen-section">
                <button
                  type="button"
                  className="mockup-gen-btn-primary"
                  onClick={handleExport}
                  disabled={exporting}
                >
                  {exporting ? 'Genererar…' : 'Generera mockup'}
                </button>
              </div>

              {exportedUrl && (
                <div className="mockup-gen-section">
                  <label className="mockup-gen-label">Klar! 🎉</label>
                  <button
                    type="button"
                    className="mockup-gen-btn-primary"
                    onClick={downloadExport}
                  >
                    Ladda ner PNG
                  </button>
                  <details style={{ marginTop: 8 }}>
                    <summary style={{ fontSize: 12, cursor: 'pointer' }}>Förhandsgranskning</summary>
                    <img
                      src={exportedUrl}
                      alt="export preview"
                      style={{ width: '100%', marginTop: 8, border: '1px solid #ccc' }}
                    />
                  </details>
                </div>
              )}

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">Verktyg</label>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 }}>
                  <input
                    type="checkbox"
                    checked={showDispPreview}
                    onChange={(e) => setShowDispPreview(e.target.checked)}
                  />
                  Visa displacement-karta
                </label>
              </div>
            </>
          )}
        </div>
      </div>

      {/* Hidden canvas for export rendering */}
      <canvas ref={canvasRef} style={{ display: 'none' }} />
    </div>
  )
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.onload = () => resolve(img)
    img.onerror = reject
    img.src = src
  })
}
