'use client'
/**
 * MockupGenerator — in-house mockup tool that replaces Printful for MBA.
 *
 * What it does:
 *   1. User picks a model template (e.g., navy tee on man)
 *   2. User uploads a design PNG (transparent background preferred)
 *   3. Design is positioned + sized on the chest area via mouse drag + slider
 *   4. Displacement-map filter (SVG <feDisplacementMap>) warps the design
 *      to follow the model's fabric folds — gives "printed-on" appearance
 *   5. Multiply blend mode ties the design's lighting to the shirt's
 *   6. User clicks "Generate" → exports a PNG that can be uploaded to Sanity
 *
 * Templates live in /public/mockup-templates/:
 *   navy-tee-male.jpg              — the model photo (1024×1024)
 *   navy-tee-male-displacement.jpg — grayscale displacement map
 *
 * To add a new template: drop a model photo + its displacement map (auto-
 * generated by the bash script in scripts/generate-displacement.sh) plus
 * a JSON entry in TEMPLATES below.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

/** Auto-crop transparent borders from a canvas. After chroma-key the design
 *  often has 30-50% transparent padding around the actual print — this trims
 *  to the bounding box of non-transparent pixels so size% reflects the print. */
function trimTransparent(src: HTMLCanvasElement): HTMLCanvasElement {
  const ctx = src.getContext('2d')
  if (!ctx) return src
  const { width, height } = src
  const data = ctx.getImageData(0, 0, width, height).data
  let minX = width, minY = height, maxX = -1, maxY = -1
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * 4 + 3] > 20) {
        if (x < minX) minX = x
        if (x > maxX) maxX = x
        if (y < minY) minY = y
        if (y > maxY) maxY = y
      }
    }
  }
  if (maxX < minX || maxY < minY) return src // all transparent
  const w = maxX - minX + 1
  const h = maxY - minY + 1
  const out = document.createElement('canvas')
  out.width = w
  out.height = h
  out.getContext('2d')!.drawImage(src, minX, minY, w, h, 0, 0, w, h)
  return out
}

type Template = {
  id: string
  label: string
  imageUrl: string
  displacementUrl: string
  /** Default chest area as % of template width/height — design auto-centers here */
  defaultChest: { x: number; y: number; width: number }
}

const TEMPLATES: Template[] = [
  {
    id: 'navy-tee-male',
    label: 'Navy Tee · Male Model',
    // Use the SAME front-view rotation frame the customer sees on /butik
    // so the admin's drag-to-position preview is a true 1:1 of what the
    // public site renders. Was /mockup-templates/navy-tee-male.jpg (a
    // different square photo of the same model) — caused subtle mismatches
    // between admin preview and customer view.
    imageUrl: '/lifestyle/rotation/frame-00.webp',
    displacementUrl: '/mockup-templates/navy-tee-male-displacement.jpg',
    // Defaults match FRAME_SPECS[0] in /lib/mockup-frames.ts so the local
    // editor's initial layout equals what server compositor renders.
    defaultChest: { x: 50, y: 45, width: 42 },
  },
]

const CANVAS_SIZE = 1024 // output dimensions

export default function MockupGenerator() {
  const [template, setTemplate] = useState<Template>(TEMPLATES[0])
  const [designUrl, setDesignUrl] = useState<string | null>(null)
  const [designName, setDesignName] = useState<string>('design')
  // Position + size as % of template (so it's resolution-independent)
  const [pos, setPos] = useState<{ x: number; y: number }>({ x: 50, y: 50 })
  // 30% default after the trim-on-chroma-key fix → the print maps to a
  // proper chest-print scale (~25 cm on a real shirt, scaled to the
  // template's 1024² frame). Was 22% — readable but looked small next
  // to a real Printful mockup.
  const [size, setSize] = useState<number>(30)
  const [displacement, setDisplacement] = useState<number>(8)
  // 'normal' default → design appears in its true colors (the color shown
  // on the AliExpress photo). Multiply was darkening designs against the
  // navy fabric, making them look faded/translucent. Still selectable
  // from the dropdown if a print really needs the fabric texture to show
  // through (e.g. a textured/heathered design).
  const [blendMode, setBlendMode] = useState<'multiply' | 'normal' | 'overlay' | 'soft-light'>('normal')
  const [opacity, setOpacity] = useState<number>(100)
  const [showDispPreview, setShowDispPreview] = useState(false)
  // NEW: shirt color picker — recolors navy shirt areas to any target color
  // (default null = keep template's original navy)
  const [shirtColor, setShirtColor] = useState<string>('#0B1220')
  const [recolorShirt, setRecolorShirt] = useState<boolean>(false)
  // NEW: remove design's background color (chroma key)
  const [removeDesignBg, setRemoveDesignBg] = useState<boolean>(true)
  // 70 handles AliExpress dual-bg photos (white margin + dark shirt fabric)
  // out of the box. Lower → preserve more print detail (good for line art);
  // higher → remove more shirt fabric (good for photos that bleed dark).
  const [bgTolerance, setBgTolerance] = useState<number>(70)
  const [exporting, setExporting] = useState(false)
  const [exportedUrl, setExportedUrl] = useState<string | null>(null)
  // Sanity integration — load products + save mockup back.
  // `cleanDesignUrl` is the transparent-bg version (manually produced via
  // remove.bg and uploaded to Sanity). When present, we use it as-is and
  // disable the live chroma-key — no algorithmic background removal needed.
  const [products, setProducts] = useState<Array<{
    _id: string; name: string; imageUrl: string; cleanDesignUrl?: string | null; sourceUrl?: string
  }>>([])
  const [selectedProductId, setSelectedProductId] = useState<string>('')
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)

  const canvasRef = useRef<HTMLCanvasElement>(null)
  const stageRef = useRef<HTMLDivElement>(null)

  // Live-preview chroma-keyed version of the design. We pre-process here on
  // EVERY designUrl / tolerance change so the user actually SEES the bg
  // removal in the stage — previously the canvas-only chroma-key meant the
  // preview was lying ("auto-remove ON" but big black square still visible).
  const [cleanedPreviewUrl, setCleanedPreviewUrl] = useState<string | null>(null)

  // Initialize position from template's default chest area
  useEffect(() => {
    setPos({ x: template.defaultChest.x, y: template.defaultChest.y })
    setSize(template.defaultChest.width)
  }, [template])

  // Live preview chroma-key — same multi-point sampling as the export path,
  // but runs in a useEffect so the on-screen design updates as you drag the
  // tolerance slider. Without this, the preview shows the raw image (with
  // its black photo bg) while the export comes out clean → confusing.
  useEffect(() => {
    if (!designUrl) { setCleanedPreviewUrl(null); return }
    if (!removeDesignBg) { setCleanedPreviewUrl(designUrl); return }
    let cancelled = false
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.onload = () => {
      if (cancelled) return
      const canvas = document.createElement('canvas')
      canvas.width = img.naturalWidth
      canvas.height = img.naturalHeight
      const ctx = canvas.getContext('2d')
      if (!ctx) return
      ctx.drawImage(img, 0, 0)
      try {
        const dData = ctx.getImageData(0, 0, canvas.width, canvas.height)
        const iw = canvas.width
        const ih = canvas.height
        const sampleAt = (x: number, y: number): [number, number, number] => {
          const i = (y * iw + x) * 4
          return [dData.data[i], dData.data[i + 1], dData.data[i + 2]]
        }
        const samples: Array<[number, number, number]> = [
          sampleAt(0, 0),
          sampleAt(iw - 1, 0),
          sampleAt(0, ih - 1),
          sampleAt(iw - 1, ih - 1),
          sampleAt(Math.floor(iw / 2), 0),
          sampleAt(Math.floor(iw / 2), ih - 1),
          sampleAt(0, Math.floor(ih / 2)),
          sampleAt(iw - 1, Math.floor(ih / 2)),
        ]
        const TOL = bgTolerance
        for (let i = 0; i < dData.data.length; i += 4) {
          const r = dData.data[i], g = dData.data[i + 1], b = dData.data[i + 2]
          let minDist = Infinity
          for (const [sr, sg, sb] of samples) {
            const d = Math.sqrt((r - sr) ** 2 + (g - sg) ** 2 + (b - sb) ** 2)
            if (d < minDist) minDist = d
            if (d < TOL) break
          }
          if (minDist < TOL) {
            dData.data[i + 3] = 0
          } else if (minDist < TOL * 1.5) {
            dData.data[i + 3] = Math.round(255 * ((minDist - TOL) / (TOL * 0.5)))
          }
        }
        ctx.putImageData(dData, 0, 0)
        // Also auto-trim the cleaned image so size% maps to the actual print,
        // not the black/white photo padding around it. Without this, a 25%
        // size slider produces a print that LOOKS 15% because half of the
        // image is empty transparent border.
        const trimmed = trimTransparent(canvas)
        setCleanedPreviewUrl(trimmed.toDataURL('image/png'))
      } catch (err) {
        console.warn('[MockupGenerator] preview chroma-key skipped:', err)
        setCleanedPreviewUrl(designUrl)
      }
    }
    img.onerror = () => setCleanedPreviewUrl(designUrl)
    img.src = designUrl
    return () => { cancelled = true }
  }, [designUrl, removeDesignBg, bgTolerance])

  // Load the product catalog from Sanity on mount.
  // Uses the same session-auth API endpoint pattern as the reservation form
  // (works because the user must be logged into Sanity Studio to access this page).
  useEffect(() => {
    const SANITY_QUERY = '*[_type=="dropshipProduct" && inStock == true] | order(order asc){_id, name, "imageUrl": image.asset->url, "cleanDesignUrl": cleanDesign.asset->url, sourceUrl}'
    fetch(`https://3zuy5n8l.api.sanity.io/v2024-01-01/data/query/production?query=${encodeURIComponent(SANITY_QUERY)}`, {
      credentials: 'include',
    })
      .then((r) => r.json())
      .then((j) => {
        if (Array.isArray(j?.result)) setProducts(j.result)
      })
      .catch((err) => {
        console.warn('[MockupGenerator] failed to load products:', err)
      })
  }, [])

  // When user picks a product, load its design.
  // Prefer `cleanDesignUrl` (pre-cleaned transparent PNG via remove.bg) when
  // present — that path produces dramatically better mockups than the
  // runtime chroma-key on the AliExpress whole-shirt photo. We also auto-
  // disable bg removal in that case (the design is already transparent;
  // running chroma-key on it would clobber print colors).
  const handleProductPick = useCallback((id: string) => {
    setSelectedProductId(id)
    setSaved(false)
    setExportedUrl(null)
    if (!id) { setDesignUrl(null); return }
    const p = products.find((x) => x._id === id)
    if (!p) return
    setDesignName(p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'))
    if (p.cleanDesignUrl) {
      setDesignUrl(p.cleanDesignUrl)
      setRemoveDesignBg(false) // already transparent — don't touch it
    } else if (p.imageUrl) {
      setDesignUrl(p.imageUrl)
      setRemoveDesignBg(true) // fall back to runtime chroma-key
    }
  }, [products])

  // Handle file upload
  const handleFile = useCallback((file: File) => {
    setDesignName(file.name.replace(/\.[^.]+$/, ''))
    const reader = new FileReader()
    reader.onload = (e) => {
      setDesignUrl(e.target?.result as string)
      setExportedUrl(null)
    }
    reader.readAsDataURL(file)
  }, [])

  const onFileInput = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const f = e.target.files?.[0]
      if (f) handleFile(f)
    },
    [handleFile],
  )

  // Drag-to-position the design on the model
  const dragging = useRef(false)
  const onPointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!designUrl) return
    dragging.current = true
    ;(e.target as HTMLElement).setPointerCapture?.(e.pointerId)
  }
  const onPointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!dragging.current || !stageRef.current) return
    const rect = stageRef.current.getBoundingClientRect()
    const x = ((e.clientX - rect.left) / rect.width) * 100
    const y = ((e.clientY - rect.top) / rect.height) * 100
    setPos({ x: Math.max(0, Math.min(100, x)), y: Math.max(0, Math.min(100, y)) })
  }
  const onPointerUp = () => { dragging.current = false }

  // Generate PNG by rendering everything to a real canvas at full resolution
  const handleExport = useCallback(async () => {
    if (!designUrl || !canvasRef.current) return
    setExporting(true)
    setExportedUrl(null)
    try {
      const canvas = canvasRef.current
      canvas.width = CANVAS_SIZE
      canvas.height = CANVAS_SIZE
      const ctx = canvas.getContext('2d')!

      // 1. Load all three images in parallel
      const [tplImg, dispImg, designImg] = await Promise.all([
        loadImage(template.imageUrl),
        loadImage(template.displacementUrl),
        loadImage(designUrl),
      ])

      // 2. Draw the template (model photo) as the base
      ctx.drawImage(tplImg, 0, 0, CANVAS_SIZE, CANVAS_SIZE)

      // 2b. SHIRT COLOR RECOLOR — if enabled, walk every pixel and replace
      // navy-blue pixels with the target color (preserving brightness).
      // The model template's shirt is navy (~#1B2540 with shading), so we
      // detect blue-dominant pixels and shift their hue. Hair/face/skin/
      // pants don't fall in the blue range so they're preserved.
      if (recolorShirt) {
        const tplData = ctx.getImageData(0, 0, CANVAS_SIZE, CANVAS_SIZE)
        const target = hexToRgb(shirtColor)
        for (let i = 0; i < tplData.data.length; i += 4) {
          const r = tplData.data[i]
          const g = tplData.data[i + 1]
          const b = tplData.data[i + 2]
          // Heuristic: pixel is "shirt navy" if blue dominates and red/green are low
          const isNavy = b > 35 && b < 110 && r < 90 && g < 90 && b > r && b > g
          if (isNavy) {
            // Preserve brightness — use the original pixel's luma to scale target
            const luma = (0.299 * r + 0.587 * g + 0.114 * b) / 60 // 0..~1 for navy range
            tplData.data[i]     = Math.min(255, target.r * luma)
            tplData.data[i + 1] = Math.min(255, target.g * luma)
            tplData.data[i + 2] = Math.min(255, target.b * luma)
          }
        }
        ctx.putImageData(tplData, 0, 0)
      }

      // 3. Render the design to an offscreen canvas with displacement applied.
      //    Canvas API doesn't have a native displacement filter, so we do it
      //    pixel-by-pixel: for each output pixel, sample the displacement
      //    map to figure out where in the design image to read from.
      const designCanvas = document.createElement('canvas')
      designCanvas.width = CANVAS_SIZE
      designCanvas.height = CANVAS_SIZE
      const dctx = designCanvas.getContext('2d')!

      // Draw design at correct position + scale
      const dWidth = (size / 100) * CANVAS_SIZE
      const dHeight = dWidth
      const dX = (pos.x / 100) * CANVAS_SIZE - dWidth / 2
      const dY = (pos.y / 100) * CANVAS_SIZE - dHeight / 2
      dctx.drawImage(designImg, dX, dY, dWidth, dHeight)

      // BACKGROUND REMOVAL — if enabled, sample the corner pixel of the
      // design (top-left within the placed bounds), then make every pixel
      // within `bgTolerance` of that color transparent. Works great for
      // designs on solid backgrounds (white, black, etc.) — same trick as
      // chroma-key green-screen, but adaptive to whatever color is in the
      // corners.
      if (removeDesignBg) {
        const ix = Math.max(0, dX)
        const iy = Math.max(0, dY)
        const iw = Math.min(dWidth, CANVAS_SIZE - ix)
        const ih = Math.min(dHeight, CANVAS_SIZE - iy)
        const dData = dctx.getImageData(ix, iy, iw, ih)

        // Multi-point chroma-key — sample 8 perimeter points (4 corners +
        // 4 mid-edges) and treat each as a distinct background color.
        // Handles AliExpress photos with white photo BG AROUND a colored
        // t-shirt: the corners catch the photo BG, the mid-edges catch
        // the t-shirt fabric. Anything matching ANY sample becomes transparent.
        const sampleAt = (x: number, y: number): [number, number, number] => {
          const i = (y * iw + x) * 4
          return [dData.data[i], dData.data[i + 1], dData.data[i + 2]]
        }
        const samples: Array<[number, number, number]> = [
          sampleAt(0, 0),
          sampleAt(iw - 1, 0),
          sampleAt(0, ih - 1),
          sampleAt(iw - 1, ih - 1),
          sampleAt(Math.floor(iw / 2), 0),
          sampleAt(Math.floor(iw / 2), ih - 1),
          sampleAt(0, Math.floor(ih / 2)),
          sampleAt(iw - 1, Math.floor(ih / 2)),
        ]

        for (let i = 0; i < dData.data.length; i += 4) {
          const r = dData.data[i]
          const g = dData.data[i + 1]
          const b = dData.data[i + 2]
          let minDist = Infinity
          for (const [sr, sg, sb] of samples) {
            const d = Math.sqrt((r - sr) ** 2 + (g - sg) ** 2 + (b - sb) ** 2)
            if (d < minDist) minDist = d
            if (d < bgTolerance) break
          }
          if (minDist < bgTolerance) {
            dData.data[i + 3] = 0
          } else if (minDist < bgTolerance * 1.5) {
            dData.data[i + 3] = Math.round(255 * ((minDist - bgTolerance) / (bgTolerance * 0.5)))
          }
        }
        dctx.putImageData(dData, ix, iy)
      }

      // 4. Apply displacement via pixel sampling
      const designData = dctx.getImageData(0, 0, CANVAS_SIZE, CANVAS_SIZE)

      // Get displacement map data
      const dispCanvas = document.createElement('canvas')
      dispCanvas.width = CANVAS_SIZE
      dispCanvas.height = CANVAS_SIZE
      dispCanvas.getContext('2d')!.drawImage(dispImg, 0, 0, CANVAS_SIZE, CANVAS_SIZE)
      const dispData = dispCanvas.getContext('2d')!.getImageData(0, 0, CANVAS_SIZE, CANVAS_SIZE)

      // Output canvas
      const outCanvas = document.createElement('canvas')
      outCanvas.width = CANVAS_SIZE
      outCanvas.height = CANVAS_SIZE
      const outData = outCanvas.getContext('2d')!.createImageData(CANVAS_SIZE, CANVAS_SIZE)

      const dispScale = displacement
      for (let y = 0; y < CANVAS_SIZE; y++) {
        for (let x = 0; x < CANVAS_SIZE; x++) {
          const dispIdx = (y * CANVAS_SIZE + x) * 4
          // Use displacement map's luminance as the displacement amount
          const lum = (dispData.data[dispIdx] + dispData.data[dispIdx + 1] + dispData.data[dispIdx + 2]) / 3
          // Map lum (0-255) to displacement (-dispScale to +dispScale)
          const dx = Math.round(((lum - 128) / 128) * dispScale)
          const dy = Math.round(((lum - 128) / 128) * dispScale)
          const srcX = Math.max(0, Math.min(CANVAS_SIZE - 1, x + dx))
          const srcY = Math.max(0, Math.min(CANVAS_SIZE - 1, y + dy))
          const srcIdx = (srcY * CANVAS_SIZE + srcX) * 4
          const outIdx = (y * CANVAS_SIZE + x) * 4
          outData.data[outIdx]     = designData.data[srcIdx]
          outData.data[outIdx + 1] = designData.data[srcIdx + 1]
          outData.data[outIdx + 2] = designData.data[srcIdx + 2]
          outData.data[outIdx + 3] = designData.data[srcIdx + 3]
        }
      }
      outCanvas.getContext('2d')!.putImageData(outData, 0, 0)

      // 5. Composite the warped design onto the template with blend mode
      ctx.globalCompositeOperation = blendMode === 'normal' ? 'source-over' : blendMode as any
      ctx.globalAlpha = opacity / 100
      ctx.drawImage(outCanvas, 0, 0)
      ctx.globalCompositeOperation = 'source-over'
      ctx.globalAlpha = 1

      // 6. Convert to PNG and offer download
      const url = canvas.toDataURL('image/png')
      setExportedUrl(url)
    } catch (err) {
      console.error('[MockupGenerator] export failed:', err)
      alert('Export failed. Check console for details.')
    } finally {
      setExporting(false)
    }
  }, [designUrl, template, pos, size, displacement, blendMode, opacity])

  // Trigger download of the exported PNG
  const downloadExport = () => {
    if (!exportedUrl) return
    const a = document.createElement('a')
    a.href = exportedUrl
    a.download = `mba-mockup-${designName}-${template.id}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
  }

  // Save the generated mockup directly back to the selected Sanity product.
  // Uploads the PNG as a Sanity asset, then patches the product's `image`
  // field with the new asset reference. Requires the user to have an active
  // Sanity Studio session (cookie auth).
  const saveToSanity = useCallback(async () => {
    if (!exportedUrl || !selectedProductId) return
    setSaving(true)
    setSaved(false)
    try {
      // 1. Convert dataURL → Blob
      const blob = await (await fetch(exportedUrl)).blob()

      // 2. Upload to Sanity assets
      const upRes = await fetch(
        'https://3zuy5n8l.api.sanity.io/v2024-01-01/assets/images/production',
        {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': blob.type || 'image/png' },
          body: blob,
        },
      )
      const upBody = await upRes.json()
      if (!upRes.ok) throw new Error(`Upload failed: ${upRes.status}`)
      const assetId = upBody?.document?._id

      // 3. Patch the product to use the new image
      const patchRes = await fetch(
        'https://3zuy5n8l.api.sanity.io/v2024-01-01/data/mutate/production',
        {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            mutations: [{
              patch: {
                id: selectedProductId,
                set: {
                  image: {
                    _type: 'image',
                    asset: { _type: 'reference', _ref: assetId },
                  },
                },
              },
            }],
          }),
        },
      )
      if (!patchRes.ok) throw new Error(`Patch failed: ${patchRes.status}`)
      setSaved(true)
    } catch (err: any) {
      console.error('[MockupGenerator] save to Sanity failed:', err)
      alert(`Save failed: ${err?.message || err}. Check console for details.`)
    } finally {
      setSaving(false)
    }
  }, [exportedUrl, selectedProductId])

  // Save ONLY the design position + size to Sanity (designX/Y/Width).
  // Separate from saveToSanity (which uploads the full composited PNG) —
  // this is the lightweight path: admin drags the design into place, clicks
  // "Save position", the server compositor at /api/mockup/[id]/0.webp
  // immediately reflects the new position on next refresh.
  const [savingPos, setSavingPos] = useState(false)
  const [savedPos, setSavedPos] = useState(false)
  const savePositionToSanity = useCallback(async () => {
    if (!selectedProductId) return
    setSavingPos(true)
    setSavedPos(false)
    try {
      const patchRes = await fetch(
        'https://3zuy5n8l.api.sanity.io/v2024-01-01/data/mutate/production',
        {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            mutations: [{
              patch: {
                id: selectedProductId,
                set: {
                  designX: pos.x,
                  designY: pos.y,
                  designWidth: size,
                },
              },
            }],
          }),
        },
      )
      if (!patchRes.ok) throw new Error(`Patch failed: ${patchRes.status}`)
      setSavedPos(true)
      // Trigger the server preview to refresh by bumping `saved` (which the
      // server-preview img URL uses as cache-buster)
      setSaved(true)
    } catch (err: any) {
      console.error('[MockupGenerator] save position failed:', err)
      alert(`Save position failed: ${err?.message || err}. Make sure you're logged into Sanity Studio.`)
    } finally {
      setSavingPos(false)
    }
  }, [selectedProductId, pos.x, pos.y, size])

  return (
    <div className="mockup-gen">
      <div className="mockup-gen-header">
        <h1>MBA Mockup Studio</h1>
        <p>Skapa produktbilder utan att betala Printful. Drag designen på modellen, justera, exportera.</p>
      </div>

      {/* Single preview = the editor below. Removed the duplicate "How
          customers see it" card 2026-05-19 — admin was seeing two views
          that didn't match (local CSS render vs. server compositor),
          which was confusing. Now the editor uses the SAME front-view
          rotation frame the customer sees on /butik (see TEMPLATES above),
          so dragging the design here is a true 1:1 of what /butik will
          render after you click "📍 Spara position". */}

      <div className="mockup-gen-grid">
        {/* LEFT: Live preview stage */}
        <div className="mockup-gen-stage-wrap">
          <div
            ref={stageRef}
            className="mockup-gen-stage"
            onPointerDown={onPointerDown}
            onPointerMove={onPointerMove}
            onPointerUp={onPointerUp}
            onPointerCancel={onPointerUp}
            style={{ touchAction: 'none' }}
          >
            <img
              src={template.imageUrl}
              alt={template.label}
              className="mockup-gen-template"
              draggable={false}
            />

            {showDispPreview && (
              <img
                src={template.displacementUrl}
                alt="displacement preview"
                className="mockup-gen-template"
                style={{ position: 'absolute', inset: 0, opacity: 0.5 }}
                draggable={false}
              />
            )}

            {designUrl && (
              <div
                className="mockup-gen-design"
                style={{
                  left: `${pos.x}%`,
                  top: `${pos.y}%`,
                  width: `${size}%`,
                  transform: 'translate(-50%, -50%)',
                  mixBlendMode: blendMode,
                  opacity: opacity / 100,
                  // Live displacement filter — fakes fabric folds in the preview.
                  // Full warping still happens at export time; this is a hint.
                  filter: displacement > 0 ? 'url(#mg-displace)' : undefined,
                }}
              >
                <img
                  src={cleanedPreviewUrl || designUrl}
                  alt="design"
                  draggable={false}
                />
              </div>
            )}

            {/* SVG filter def — referenced from .mockup-gen-design's filter:url(#mg-displace)
                so the live preview can warp the design along the shirt's fabric folds. */}
            <svg
              width="0"
              height="0"
              style={{ position: 'absolute', pointerEvents: 'none' }}
              aria-hidden="true"
            >
              <defs>
                <filter id="mg-displace" x="-10%" y="-10%" width="120%" height="120%">
                  <feImage
                    href={template.displacementUrl}
                    preserveAspectRatio="xMidYMid slice"
                    result="dispMap"
                  />
                  <feDisplacementMap
                    in="SourceGraphic"
                    in2="dispMap"
                    scale={displacement}
                    xChannelSelector="R"
                    yChannelSelector="G"
                  />
                </filter>
              </defs>
            </svg>

            {!designUrl && (
              <div className="mockup-gen-placeholder">
                <div>↑</div>
                <div>Ladda upp en design för att börja</div>
              </div>
            )}
          </div>
        </div>

        {/* RIGHT: Controls */}
        <div className="mockup-gen-controls">
          <div className="mockup-gen-section">
            <label className="mockup-gen-label">1. Välj modell</label>
            <select
              value={template.id}
              onChange={(e) =>
                setTemplate(TEMPLATES.find((t) => t.id === e.target.value) || TEMPLATES[0])
              }
            >
              {TEMPLATES.map((t) => (
                <option key={t.id} value={t.id}>{t.label}</option>
              ))}
            </select>
          </div>

          {/* NEW — Load directly from Sanity. Skips the manual download
              of AliExpress photo → upload to studio cycle entirely. */}
          {products.length > 0 && (
            <div className="mockup-gen-section" style={{
              background: 'rgba(255, 203, 5, 0.10)',
              padding: 14,
              borderRadius: 6,
              border: '1px solid rgba(255, 203, 5, 0.35)',
            }}>
              <label className="mockup-gen-label">
                ⚡ Snabbladda från Sanity
              </label>
              <select
                value={selectedProductId}
                onChange={(e) => handleProductPick(e.target.value)}
              >
                <option value="">— Välj en produkt —</option>
                {products.map((p) => (
                  <option key={p._id} value={p._id}>{p.name}</option>
                ))}
              </select>
              <div style={{ fontSize: 11, opacity: 0.7, marginTop: 6 }}>
                Laddar produktbilden från Sanity direkt. Ingen nedladdning behövs.
              </div>
            </div>
          )}

          <div className="mockup-gen-section">
            <label className="mockup-gen-label">2. Ladda upp design (PNG)</label>
            <div style={{ fontSize: 11, opacity: 0.6, marginBottom: 4 }}>
              … eller ladda upp en egen fil:
            </div>
            <input
              type="file"
              accept="image/png,image/jpeg,image/webp"
              onChange={onFileInput}
            />
            {designUrl && (
              <button
                type="button"
                className="mockup-gen-btn-ghost"
                onClick={() => {
                  setDesignUrl(null)
                  setExportedUrl(null)
                  setSelectedProductId('')
                  setSaved(false)
                }}
              >
                Ta bort design
              </button>
            )}
          </div>

          {designUrl && (
            <>
              {/* NEW — Background removal for the uploaded design. Defaults
                  to ON so users who upload a full t-shirt photo (with shirt
                  outline visible) get the print isolated automatically. */}
              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  Bakgrund på design
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 }}>
                  <input
                    type="checkbox"
                    checked={removeDesignBg}
                    onChange={(e) => setRemoveDesignBg(e.target.checked)}
                  />
                  Ta bort designens bakgrund automatiskt
                </label>
                {removeDesignBg && (
                  <>
                    <label className="mockup-gen-label" style={{ marginTop: 8 }}>
                      Tolerans <span>({bgTolerance})</span>
                    </label>
                    <input
                      type="range"
                      min="10"
                      max="150"
                      step="5"
                      value={bgTolerance}
                      onChange={(e) => setBgTolerance(Number(e.target.value))}
                    />
                    <div style={{ fontSize: 11, opacity: 0.6, marginTop: 2 }}>
                      Mer = tar bort fler färger. Mindre = bevarar fler detaljer.
                    </div>
                  </>
                )}
              </div>

              {/* NEW — Shirt color picker. Replaces every navy pixel in the
                  template with the chosen color, preserving fabric shading.
                  Lets one model template serve products of any shirt color. */}
              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  Tröjans färg
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 }}>
                  <input
                    type="checkbox"
                    checked={recolorShirt}
                    onChange={(e) => setRecolorShirt(e.target.checked)}
                  />
                  Byt tröjfärg
                </label>
                {recolorShirt && (
                  <>
                    <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 8 }}>
                      <input
                        type="color"
                        value={shirtColor}
                        onChange={(e) => setShirtColor(e.target.value)}
                        style={{ width: 48, height: 32, padding: 0, border: '1px solid rgba(11,18,32,0.18)', borderRadius: 4 }}
                      />
                      <input
                        type="text"
                        value={shirtColor}
                        onChange={(e) => setShirtColor(e.target.value)}
                        style={{ flex: 1, padding: 8, fontSize: 12, border: '1px solid rgba(11,18,32,0.18)', borderRadius: 4, fontFamily: 'var(--mono)' }}
                      />
                    </div>
                    <div style={{ display: 'flex', gap: 6, marginTop: 8, flexWrap: 'wrap' }}>
                      {[
                        { c: '#000000', name: 'Svart' },
                        { c: '#FFFFFF', name: 'Vit' },
                        { c: '#0B1220', name: 'Marin' },
                        { c: '#FFCB05', name: 'Gul' },
                        { c: '#7A0E0E', name: 'Röd' },
                        { c: '#3a5f3a', name: 'Grön' },
                        { c: '#888', name: 'Grå' },
                      ].map((sw) => (
                        <button
                          key={sw.c}
                          type="button"
                          onClick={() => setShirtColor(sw.c)}
                          title={sw.name}
                          style={{
                            width: 24, height: 24, borderRadius: 4,
                            background: sw.c,
                            border: shirtColor === sw.c ? '2px solid var(--yellow)' : '1px solid rgba(11,18,32,0.2)',
                            cursor: 'pointer', padding: 0,
                          }}
                        />
                      ))}
                    </div>
                    <div style={{ fontSize: 11, opacity: 0.6, marginTop: 6 }}>
                      Färgar om marinblå tröjpixlar till vald färg. Hud/hår/byxor påverkas inte.
                    </div>
                  </>
                )}
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  3. Storlek <span>({size.toFixed(0)}%)</span>
                </label>
                <input
                  type="range"
                  min="3"
                  max="35"
                  step="1"
                  value={size}
                  onChange={(e) => setSize(Number(e.target.value))}
                />
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  4. Position
                </label>
                <div style={{ fontSize: 12, opacity: 0.7 }}>
                  Drag designen på bilden för att flytta · X: {pos.x.toFixed(0)}% Y: {pos.y.toFixed(0)}%
                </div>
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  5. Tygveckning <span>({displacement}px)</span>
                </label>
                <input
                  type="range"
                  min="0"
                  max="25"
                  step="1"
                  value={displacement}
                  onChange={(e) => setDisplacement(Number(e.target.value))}
                />
                <div style={{ fontSize: 11, opacity: 0.6, marginTop: 4 }}>
                  Hur mycket designen följer tygets veck. Mer = mer realistiskt, men kan distorsera.
                </div>
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  6. Blend mode
                </label>
                <select
                  value={blendMode}
                  onChange={(e) => setBlendMode(e.target.value as any)}
                >
                  <option value="multiply">Multiply (best för mörk t-shirt)</option>
                  <option value="overlay">Overlay (mer kontrast)</option>
                  <option value="soft-light">Soft Light (mjukare)</option>
                  <option value="normal">Normal (helt opak)</option>
                </select>
              </div>

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">
                  7. Opacitet <span>({opacity}%)</span>
                </label>
                <input
                  type="range"
                  min="20"
                  max="100"
                  step="1"
                  value={opacity}
                  onChange={(e) => setOpacity(Number(e.target.value))}
                />
              </div>

              <div className="mockup-gen-section">
                <button
                  type="button"
                  className="mockup-gen-btn-primary"
                  onClick={handleExport}
                  disabled={exporting}
                >
                  {exporting ? 'Genererar…' : 'Generera mockup'}
                </button>

                {/* NEW: lightweight "save position" — just persists X/Y/Width
                    to Sanity so the server compositor at /api/mockup/[id]/0
                    matches the local editor exactly. No PNG upload. */}
                {selectedProductId && (
                  <button
                    type="button"
                    className="mockup-gen-btn-ghost"
                    onClick={savePositionToSanity}
                    disabled={savingPos}
                    style={{ marginTop: 8 }}
                    title="Saves design X/Y position + width to Sanity so the customer-facing /butik shows the print in the same spot you positioned it here."
                  >
                    {savingPos ? 'Sparar position…' : savedPos ? '✓ Position sparad' : '📍 Spara position (X/Y/storlek)'}
                  </button>
                )}
              </div>

              {exportedUrl && (
                <div className="mockup-gen-section">
                  <label className="mockup-gen-label">Klar! 🎉</label>

                  {/* Primary CTA: save back to Sanity (if a product was picked) */}
                  {selectedProductId && (
                    <button
                      type="button"
                      className="mockup-gen-btn-primary"
                      onClick={saveToSanity}
                      disabled={saving || saved}
                      style={{ marginBottom: 8 }}
                    >
                      {saving ? 'Sparar…' : saved ? '✓ Sparad i Sanity' : '⚡ Spara till Sanity-produkt'}
                    </button>
                  )}

                  {/* Always available: download as PNG (use case: save locally
                      to upload to a different product, or use elsewhere) */}
                  <button
                    type="button"
                    className="mockup-gen-btn-ghost"
                    onClick={downloadExport}
                  >
                    Ladda ner PNG
                  </button>

                  {saved && (
                    <div style={{
                      fontSize: 12,
                      marginTop: 8,
                      padding: 8,
                      background: '#e8f5e8',
                      borderRadius: 4,
                      color: '#1b5e20',
                    }}>
                      ✓ Mockup uppladdad. Hård-refresha{' '}
                      <a href="/butik" target="_blank" rel="noopener">/butik</a>
                      {' '}om ~60 sekunder för att se den live.
                    </div>
                  )}

                  <details style={{ marginTop: 8 }}>
                    <summary style={{ fontSize: 12, cursor: 'pointer' }}>Förhandsgranskning</summary>
                    <img
                      src={exportedUrl}
                      alt="export preview"
                      style={{ width: '100%', marginTop: 8, border: '1px solid #ccc' }}
                    />
                  </details>
                </div>
              )}

              <div className="mockup-gen-section">
                <label className="mockup-gen-label">Verktyg</label>
                <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 }}>
                  <input
                    type="checkbox"
                    checked={showDispPreview}
                    onChange={(e) => setShowDispPreview(e.target.checked)}
                  />
                  Visa displacement-karta
                </label>
              </div>
            </>
          )}
        </div>
      </div>

      {/* Hidden canvas for export rendering */}
      <canvas ref={canvasRef} style={{ display: 'none' }} />
    </div>
  )
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.onload = () => resolve(img)
    img.onerror = reject
    img.src = src
  })
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const m = hex.replace('#', '').match(/.{2}/g)
  if (!m) return { r: 0, g: 0, b: 0 }
  return {
    r: parseInt(m[0], 16),
    g: parseInt(m[1], 16),
    b: parseInt(m[2], 16),
  }
}
